### ISSUE TITLE
[SDKCLI-11] Handle Job Logs

### ISSUE THREAD

**Issue by yoannfleurydev** [saagie/sdk#11]

**Comment by yoannfleurydev** [comment]
Waiting for discussion with Saagie Back End

**Comment by PierreLeresteux** [comment]
Here is a proposal for the returning format : 
```
{
    "log" : string,
    "stream" : string [stdout|stderr],
    "time" : string(datetime)
}
```

**log** : A String representing the log 
**stream** : stdout or stderr to know how to display this log 
**time** : a  local date time [ISO 8601](https://fr.wikipedia.org/wiki/ISO_8601) representation in String
