### ISSUE TITLE
[SDKCLI-17] Manage all status from design system

### ISSUE THREAD

**Issue by youenchene** [saagie/sdk#17]
https://7-design-system.public.prod.saagie.io/v/latest/docs-pages-ui-projects-status

After discussion with @yoannfleurydev :

This status are displayed : 
QUEUED, RUNNING, SUCCEEDED, KILLING, KILLED, FAILED.

If another status come from the job : 
- it display the raw status
- display a message that says that the status is not supported for job with a reference to the design system.

**Comment by yoannfleurydev** [comment]
Can you explain a little bit more about what you want? :thinking:

**Comment by PierreLeresteux** [comment]
I think he wants that all mapped status can be displayed.
- On start => **QUEUED**, **RUNNING** or **FAILED** (QUEUED when start don't know if the start is correctly effective in the external service, RUNNING when the start is good, and FAILED if not)
- On status => **QUEUED**, **RUNNING**, **SUCCEEDED**, **KILLED** or **FAILED** (QUEUED if the service is still not effective, RUNNING if the service is in progress, SUCCEEDED if the job is successfully finished and FAILED for any errors)
- On stop => **KILLED** or **FAILED** (KILLED if the process was stop, FAILED if there is an error during the STOP call)

That's I have understood about this issue ...

**Comment by youenchene** [comment]
Content of the issue have been updated.
