### ISSUE TITLE
[SDKCLI-56] Invalid Version: undefined

### ISSUE THREAD

**Issue by yoannfleurydev** [saagie/sdk#94]
**Describe the bug**
Just right after creating my technology and context, when I select the endpoint form, the Dataset select box is throwing an error.

**To Reproduce**
1. Create a technology
2. Create a context
3. Put the `http://localhost:4000` in the endpoint URL
4. Select the endpoint in the select box
5. See the error in the Dataset select box

**Expected behavior**
No error

**Screenshots**

![image (1)](https://user-images.githubusercontent.com/3920615/110125171-513d5200-7dc3-11eb-9a16-83efe05212a9.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all
 - `@saagie/sdk` 0.12.2

**Comment by fabienmifsud** [comment]
Fixed in version 0.12.3
